export const INPUT_VALUE = 'INPUT_VALUE';
export const CHARACTER_REQUEST_STARTED = 'CHARACTER_REQUEST_STARTED';
export const CHARACTER_REQUEST_SUCCESS = 'CHARACTER_REQUEST_SUCCESS';
export const CHARACTER_REQUEST_FAILED = 'CHARACTER_REQUEST_FAILED';